name: 'Advanced Security PR Alerts CSV'
description: 'Gets code scanning alerts from PRs and generates a CSV.'

branding:
  icon: 'file-text'
  color: 'green'

inputs:
  TOKEN:
    description: 'GitHub Token or Personal Access Token  - must use PAT to access alerts for repos other
      than the repo where the action is used.'
    required: true
  path:
    description: 'Path to the directory where the csv file should be saved.'
    required: true
  total_days:
    description: 'Integer - fetches PRs for the past total_days. For example, if total_days is set `7`,
      the action will get code scanning alerts on PRs that have been updated in the past seven days.
      Minimum is 1 day and max is 365 days. Defaults to `30`.'
    required: false
  repos:
    description: 'Comma-separated list of repository names from which PR code scanning alerts should be
      fetched. For example, `best-app,cool-app`. The repos must be in the org where the action is used.
      Set to `all` for PR code scanning alerts from all repos in the org. When `repos` is not set, the
      action will get PR code scanning alerts for the repo where it is used. When `repos` is set, include
      the repo where the action is used to get PR code scanning alerts for that repo.'
    required: false
  include_ref_alerts:
    description: 'Set to `true` to include all alerts surfaced on the merge or head branches of the PRs.
      When set to `false`, the only alerts included will be alerts that were surfaced in the comments on
      the PRs. Alerts surfaced in comments indicate vulnerabilities introduced by the code changes in the
      PR. Defaults to `false`.'

runs:
  using: 'node20'
  main: 'dist/index.js'
